# Generated by Django 4.2.11 on 2024-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Renewal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merchant_id", models.CharField(max_length=20)),
                ("merchant_user_id", models.CharField(max_length=20)),
                ("transaction_id", models.CharField(max_length=20)),
                ("subscription_id", models.CharField(max_length=20)),
                ("notification_id", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "renewals_debit_execute_table",
            },
        ),
    ]
