# Generated by Django 4.2.11 on 2024-03-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merchant_id", models.CharField(max_length=20)),
                ("merchant_user_id", models.CharField(max_length=20)),
                ("subscription_id", models.CharField(max_length=20)),
                ("transaction_id", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("amount", models.IntegerField()),
                ("auto_debit", models.BooleanField(default=False)),
                ("state", models.CharField(max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notifications_table",
            },
        ),
    ]
